import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "src/dict/**", // generated by sync:opencc
      "data/official/**", // downloaded by sync:opencc
      "coverage/**",
      "*.log",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "no-console": "off", // CLI scripts and dev warnings need it
    },
  },
  {
    // Build / config / Node-CLI scripts: looser rules.
    files: ["rollup.config.js", "eslint.config.js", "scripts/**/*.ts", "vitest.config.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];
