/**
 * Sync dictionaries from OpenCC official repository
 *
 * Usage: npx tsx scripts/sync-opencc.ts
 */

import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");

// OpenCC dictionary source
const OPENCC_BASE_URL = "https://raw.githubusercontent.com/BYVoid/OpenCC/master/data/dictionary";

// Dictionary files available in OpenCC official repo (based on API check)
const OFFICIAL_DICT_FILES = [
  "HKVariants",
  "HKVariantsRevPhrases",
  "JPShinjitaiCharacters",
  "JPShinjitaiPhrases",
  "STCharacters",
  "STPhrases",
  "TSCharacters",
  "TSPhrases",
  "TWPhrases",
  "TWPhrasesRev",
  "TWVariants",
  "TWVariantsRevPhrases",
];

// Reverse dictionaries to generate (not available in OpenCC, need to create from forward dicts)
const REVERSE_DICT_MAPPINGS: Record<string, string> = {
  HKVariantsRev: "HKVariants",
  TWVariantsRev: "TWVariants",
  // Upstream OpenCC #1302 (2026-06-11) removed JPVariants.txt, folding its
  // character data into JPShinjitaiCharacters.txt; t2jp is now generated by
  // reversing JPShinjitaiCharacters (see src/presets.ts jp mappings).
  JPShinjitaiCharactersRev: "JPShinjitaiCharacters",
};

/**
 * Discover the current list of .txt dictionary files in OpenCC's master branch
 * via the GitHub API. Used to detect upstream additions/removals that our
 * hardcoded OFFICIAL_DICT_FILES list might miss.
 */
async function listUpstreamDictFiles(): Promise<string[] | null> {
  const apiUrl = "https://api.github.com/repos/BYVoid/OpenCC/contents/data/dictionary?ref=master";
  try {
    const response = await fetch(apiUrl);
    if (!response.ok) {
      console.warn(`  GitHub API discovery skipped: ${response.status} ${response.statusText}`);
      return null;
    }
    const data = await response.json() as Array<{ name: string; type: string }>;
    return data
      .filter((entry) => entry.type === "file" && entry.name.endsWith(".txt"))
      .map((entry) => entry.name.replace(/\.txt$/, ""));
  } catch (e) {
    console.warn(`  GitHub API discovery skipped: ${(e as Error).message}`);
    return null;
  }
}

async function downloadFile(fileName: string): Promise<string> {
  const url = `${OPENCC_BASE_URL}/${fileName}.txt`;
  console.log(`  Downloading ${fileName}...`);

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download ${fileName}: ${response.status}`);
  }

  const content = await response.text();

  // Sanity check: reject HTML error pages or other unexpected content.
  // Real dict files are UTF-8 text starting with a CJK character or comment ('#').
  const trimmedStart = content.trimStart();
  if (trimmedStart.startsWith("<") || trimmedStart.startsWith("{") || trimmedStart.startsWith("[")) {
    throw new Error(
      `Downloaded ${fileName} appears to be ${trimmedStart.startsWith("<") ? "HTML" : "JSON"}, not a dict file. ` +
      `First 80 chars: ${trimmedStart.slice(0, 80)}`
    );
  }

  return content;
}

function parseToEntries(content: string, isCustom: boolean = false): [string, string][] {
  return content
    .trim()
    .split(/\r?\n/)
    .map((rawLine) => {
      // Trim BEFORE the comment test: the no-tab fallback below matches on a
      // trimmed line, so an indented `  # 交通` would otherwise parse as the
      // entry `# → 交通` and rewrite every `#` in converted text.
      const line = rawLine.trim();
      if (!line || line.startsWith("#")) return null;

      // Tab is the normal separator, but some entries (and hand-edited custom
      // ones) use spaces — accept a whitespace run too, matching the runtime
      // parser in core.ts. Splitting on the FIRST run keeps multi-token values.
      const tabIdx = line.indexOf("\t");
      // A second tab ends the value field in both dict flavours — everything
      // after it is a trailing comment/column, never part of the value.
      const m = tabIdx >= 0 ? [line.slice(0, tabIdx), line.slice(tabIdx + 1).split("\t")[0]] : line.match(/^(\S+)\s+(.+)$/)?.slice(1);
      if (!m) return null;
      const [key, values] = m;
      if (!key || !values) return null;

      // Official dicts list space-separated candidates and the first wins;
      // a custom entry is ONE value that may contain spaces (二维码 → "QR Code").
      const value = isCustom ? values.trim() : values.trim().split(/\s+/)[0];
      return [key.trim(), value] as [string, string];
    })
    .filter((entry): entry is [string, string] => entry !== null && !!entry[0] && !!entry[1]);
}

function entriesToOptimized(entries: [string, string][]): string {
  // Packed format: entries joined by "|", key/value split on FIRST space
  // (Trie.loadDict string form). A "|" anywhere or a space in a KEY would
  // silently corrupt every entry after it — fail the sync loudly instead.
  // Values MAY contain spaces (custom dicts, e.g. 二维码 → "QR Code").
  for (const [k, v] of entries) {
    if (k.includes("|") || v.includes("|") || /\s/.test(k)) {
      throw new Error(`Dict entry breaks packed format (space in key or "|"): ${JSON.stringify([k, v])}`);
    }
  }
  return entries
    .filter(([k, v]) => k !== v || k.length > 1) // Remove identity mappings for single chars
    .map(([k, v]) => `${k} ${v}`)
    .join("|");
}

function reverseEntries(entries: [string, string][]): [string, string][] {
  // Reverse mapping: value -> key. When several keys collapse onto one value
  // (HKVariants has both 才→才 and 纔→才), the IDENTITY pair must win: the
  // trie is last-wins, so keeping all entries shipped 才→纔, 煙→菸, 核→覈,
  // 梁→樑 — and entriesToOptimized then dropped the correct single-char
  // identity pair, leaving only the wrong mapping. Char-level reversal falls
  // back to identity; the *RevPhrases dicts disambiguate in context (上梁→上樑).
  // Non-identity collisions (none upstream today) keep the first entry.
  const reversed = new Map<string, string>();
  for (const [k, v] of entries) {
    if (!reversed.has(v) || k === v) {
      reversed.set(v, k);
    }
  }
  return [...reversed.entries()];
}

async function main() {
  const officialDir = path.join(ROOT_DIR, "data", "official");
  const dictDir = path.join(ROOT_DIR, "src", "dict");

  // Create directories
  fs.mkdirSync(officialDir, { recursive: true });
  fs.mkdirSync(dictDir, { recursive: true });

  console.log("Syncing dictionaries from OpenCC...\n");

  console.log("Discovering upstream dict files via GitHub API...");
  const upstreamFiles = await listUpstreamDictFiles();
  if (upstreamFiles) {
    const known = new Set(OFFICIAL_DICT_FILES);
    const upstream = new Set(upstreamFiles);
    const added = upstreamFiles.filter((f) => !known.has(f));
    const removed = OFFICIAL_DICT_FILES.filter((f) => !upstream.has(f));
    if (added.length > 0) {
      console.warn(`⚠️  Upstream has new dict file(s) not in OFFICIAL_DICT_FILES: ${added.join(", ")}`);
      console.warn(`   If these are needed, add to OFFICIAL_DICT_FILES in scripts/sync-opencc.ts.`);
    }
    if (removed.length > 0) {
      console.warn(`⚠️  OFFICIAL_DICT_FILES references file(s) not present upstream: ${removed.join(", ")}`);
      console.warn(`   These will 404 during download. Update OFFICIAL_DICT_FILES.`);
    }
    if (added.length === 0 && removed.length === 0) {
      console.log("✓ OFFICIAL_DICT_FILES is in sync with upstream.");
    }
  } else {
    console.log("Skipping file-list comparison (no API response).");
  }
  console.log("");

  const allEntries: Record<string, [string, string][]> = {};
  const officialContents: Record<string, string> = {};

  // Download official dictionaries. Failures abort the script — partial syncs
  // would produce an inconsistent manifest and a bad release.
  console.log("1. Downloading official dictionaries:");
  for (const fileName of OFFICIAL_DICT_FILES) {
    const content = await downloadFile(fileName);

    // Save raw file to data/official/
    const rawPath = path.join(officialDir, `${fileName}.txt`);
    fs.writeFileSync(rawPath, content, "utf-8");

    // Parse entries
    const entries = parseToEntries(content);

    // Sanity check: official dicts must have at least one entry.
    // Zero entries signals corruption or a format change.
    if (entries.length === 0) {
      throw new Error(
        `Parsed zero entries from ${fileName}. Source may be corrupted or format has changed.`
      );
    }

    allEntries[fileName] = entries;
    officialContents[fileName] = content;

    // Save optimized format to src/dict/. Use JSON.stringify (not manual
    // quotes) so any `"`, `\`, or control char in upstream data is escaped —
    // otherwise a single such char would emit a broken .ts file and fail the
    // build (and silently halt the automated biweekly publish).
    const optimized = entriesToOptimized(entries);
    const dictPath = path.join(dictDir, `${fileName}.ts`);
    fs.writeFileSync(dictPath, `export default ${JSON.stringify(optimized)};\n`, "utf-8");

    console.log(`    ✓ ${fileName} (${entries.length} entries)`);
  }

  // Generate reverse dictionaries
  console.log("\n2. Generating reverse dictionaries:");
  for (const [revName, srcName] of Object.entries(REVERSE_DICT_MAPPINGS)) {
    const srcEntries = allEntries[srcName];
    if (!srcEntries) {
      console.log(`    ⚠ ${revName}: Source ${srcName} not found`);
      continue;
    }

    const entries = reverseEntries(srcEntries);

    // Save reverse dict (JSON.stringify escapes any special chars — see above).
    const optimized = entriesToOptimized(entries);
    const dictPath = path.join(dictDir, `${revName}.ts`);
    fs.writeFileSync(dictPath, `export default ${JSON.stringify(optimized)};\n`, "utf-8");

    console.log(`    ✓ ${revName} (${entries.length} entries, from ${srcName})`);
  }

  // Generate dict index file
  const allDictNames = [...OFFICIAL_DICT_FILES, ...Object.keys(REVERSE_DICT_MAPPINGS)];

  // Process Custom Dictionaries
  console.log("\n3. Processing custom dictionaries:");
  const customDataDir = path.join(ROOT_DIR, "data", "custom");
  const customDataFiles = ["CNTWPhrases"];

  // Failures here abort the sync, same as official dicts. Custom dicts used to
  // warn-and-continue, but the UMD bundles now import src/dict/CNTWPhrases.js
  // statically: a skipped file leaves the bundles on stale data (or fails tsc)
  // while the main entry silently ships without the phrase dict — the npm/UMD
  // divergence this release exists to remove, hidden behind a "✓ Sync complete!".
  for (const name of customDataFiles) {
    const p = path.join(customDataDir, `${name}.txt`);
    if (!fs.existsSync(p)) {
      throw new Error(`Custom dict ${name}.txt missing from data/custom/ — the bundles import it directly.`);
    }
    const content = fs.readFileSync(p, "utf-8");
    // isCustom: keep the WHOLE value ("QR Code"), don't truncate to the
    // first space-separated token like official multi-candidate dicts.
    const entries = parseToEntries(content, true);
    const optimized = entriesToOptimized(entries);
    const dictPath = path.join(dictDir, `${name}.ts`);
    fs.writeFileSync(dictPath, `export default ${JSON.stringify(optimized)};\n`, "utf-8");
    allDictNames.push(name);
    console.log(`    ✓ ${name} (${entries.length} entries)`);
  }

  // Lazy loader map — one dynamic import per dict file so bundlers code-split
  // each dictionary into its own chunk and consumers fetch only what a
  // conversion direction needs (STPhrases alone is ~1MB; t→cn needs ~40KB).
  // Eager consumers (UMD bundles) import the dict files directly instead.
  const indexContent =
    "export const dictLoaders: Record<string, () => Promise<{ default: string }>> = {\n" +
    allDictNames.map((name) => `  ${name}: () => import('./${name}.js'),`).join("\n") +
    "\n};\n";
  fs.writeFileSync(path.join(dictDir, "index.ts"), indexContent, "utf-8");

  // Write tracked manifest of upstream dict content hashes.
  // CI watches this file's git diff to decide whether to publish.
  // Hashing the raw upstream text (not generated .ts output) means changes in
  // our generation algorithm don't trigger spurious "upstream changed" releases.
  const sortedNames = Object.keys(officialContents).sort();
  const fileHashes: Record<string, string> = {};
  for (const name of sortedNames) {
    const h = crypto.createHash("sha256").update(officialContents[name], "utf8").digest("hex");
    fileHashes[name] = `sha256:${h}`;
  }
  const manifest = {
    _comment:
      "Auto-generated by `npm run sync:opencc`. Tracks upstream OpenCC dict content " +
      "hashes for CI change detection. CI publishes a new release iff this file changes. " +
      "Do not edit by hand.",
    upstream: "https://github.com/BYVoid/OpenCC/tree/master/data/dictionary",
    files: fileHashes,
  };
  const manifestPath = path.join(ROOT_DIR, ".opencc-sync.json");
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf-8");

  console.log("\n✓ Sync complete!");
  console.log(`  Raw files: data/official/ (${OFFICIAL_DICT_FILES.length} files)`);
  console.log(`  Dict modules: src/dict/ (${allDictNames.length} files)`);
  console.log(`  Manifest:    .opencc-sync.json`);
}

main().catch((err) => {
  console.error("sync:opencc failed:", err);
  process.exit(1);
});
