/**
 * OpenCC JS - Converter Builder
 * High-level API for creating converters
 */

// Imports removed

import { ConverterFactory, ProtectedConverter, DictGroup, DictLike, parseOpenCCDict } from "./core.js";
import { variants2standard, standard2variants, LocaleCode } from "./presets.js";

// Dict modules will be generated by sync-opencc script
// Import them dynamically or statically after running sync

/**
 * Converter options
 */
export interface ConverterOptions {
  /** Source locale code */
  from: LocaleCode;
  /** Target locale code */
  to: LocaleCode;
  /** Whether to load custom phrase dictionary (default: true for twp) */
  loadCustomPhrases?: boolean;
}

/**
 * Locale preset data containing dictionary groups
 */
export interface LocalePreset {
  from: Record<string, DictGroup>;
  to: Record<string, DictGroup>;
}

/**
 * Create a Converter factory with locale preset
 * @param localePreset - Preset containing dictionary groups for each locale
 * @returns Converter factory function
 */
export function ConverterBuilder(localePreset: LocalePreset) {
  return function Converter(options: ConverterOptions): (input: string) => string {
    const dictGroups: DictGroup[] = [];

    // Add 'from' dictionaries (variant -> standard)
    if (options.from !== "t" && localePreset.from[options.from]) {
      dictGroups.push(localePreset.from[options.from]);
    }

    // Add 'to' dictionaries (standard -> variant)
    if (options.to !== "t" && localePreset.to[options.to]) {
      dictGroups.push(localePreset.to[options.to]);
    }

    return ConverterFactory(...dictGroups);
  };
}

/**
 * Dictionary files for a conversion, GROUPED BY CONVERSION STEP.
 *
 * Returns `string[][]`: each inner array is one conversion step
 * (variant→standard, then standard→variant). Each step MUST be loaded into a
 * SINGLE merged trie so the trie's longest-match lets phrase dictionaries
 * (STPhrases, *RevPhrases) win over single-character dictionaries.
 *
 * Correct usage:
 *   ConverterFactory(...getDictFiles(from, to).map(group => buildTrieFromGroup(group)))
 *
 * Do NOT flatten the groups and run each file as its own group — that converts
 * characters first, so the phrase dict's source keys no longer exist and every
 * phrase dictionary becomes dead code (头发→頭發 instead of 頭髮). That flat-list
 * mental model is exactly what this grouped return type exists to prevent. If you
 * only need the flat file list (e.g. to know which dict files to bundle), call
 * `getDictFiles(from, to).flat()`.
 *
 * @throws {Error} if `from` or `to` is an unknown locale (i.e. not `'t'` and not
 *   a key of `variants2standard` / `standard2variants`).
 */
export function getDictFiles(from: LocaleCode, to: LocaleCode): string[][] {
  const groups: string[][] = [];

  if (from !== "t") {
    const fromFiles = variants2standard[from];
    // Reject unknown locales loudly instead of silently producing a converter
    // that skips the step (which would return partially/un-converted text).
    if (!fromFiles) throw new Error(`Unknown 'from' locale: ${from}`);
    if (fromFiles.length) groups.push(fromFiles);
  }

  if (to !== "t") {
    const toFiles = standard2variants[to];
    if (!toFiles) throw new Error(`Unknown 'to' locale: ${to}`);
    if (toFiles.length) groups.push(toFiles);
  }

  return groups;
}

/**
 * Try to auto-load the bundled `data/custom/ProtectedDict.txt`. Returns undefined in
 * browsers/Deno, on any I/O error, or when the file parses to zero entries.
 * Resolves via `import.meta.url` so it works in both source (tsx) and
 * built (dist) environments.
 */
async function tryLoadPackageProtectedDict(): Promise<DictLike | undefined> {
  try {
    const fsMod = await import("node:fs/promises");
    const urlMod = await import("node:url");
    // converter.{ts,js} is one level deep under (src|dist); data/ is sibling.
    const filePath = urlMod.fileURLToPath(new URL("../data/custom/ProtectedDict.txt", import.meta.url));
    const text = await fsMod.readFile(filePath, "utf8");
    const parsed = parseOpenCCDict(text);
    return parsed.length > 0 ? parsed : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Load dictionaries and create a converter.
 *
 * @param options - Converter options (locale, optional flags)
 * @param protectedDict - Hard-override dictionary. Matches are masked with PUA
 *   placeholders before built-in conversion runs, then restored after — OpenCC
 *   built-in dictionaries never see or modify them. Highest priority.
 *
 *   If omitted, `createConverter` auto-loads the bundled `data/custom/ProtectedDict.txt`
 *   (Node-only convenience). Pass an explicit value (including `[]`) to bypass.
 *
 *   **Breaking change in v1.3.1:** Replaces v1.0.x's `customDict` (soft
 *   override). If you depended on chained A→B (custom) → B→C (standard),
 *   rewrite as A→C directly.
 */
export async function createConverter(
  options: ConverterOptions,
  protectedDict?: DictLike
): Promise<(input: string) => string> {
  // Warn JS callers still passing the removed v1.0.x option. TypeScript catches
  // this as an excess property, but JS users wouldn't see the breakage otherwise.
  if (options && typeof options === "object" && "applyCharFixes" in options) {
    console.warn(
      "[js-opencc] The `applyCharFixes` option was removed in v1.3.x. " +
        "CharFixes.txt is replaced by `protectedDict` (hard override) — see README migration section."
    );
  }
  // Auto-load bundled data/custom/ProtectedDict.txt if no explicit dict provided
  if (!protectedDict) {
    protectedDict = await tryLoadPackageProtectedDict();
  }
  const dictGroups: DictGroup[] = [];

  const dictModules = await import("./dict/index.js");

  const loadDictFromModule = (name: string): string[][] | null => {
    const dictData = (dictModules as Record<string, string>)[name];
    if (!dictData) return null;
    return dictData.split("|").map((entry) => {
      const parts = entry.split(" ");
      const k = parts[0];
      const v = parts.slice(1).join(" ");
      return [k, v || k];
    });
  };

  // (a) Built-in dictionaries — loaded per conversion-step group from
  // getDictFiles. Each step is ONE merged trie so the trie's longest-match lets
  // phrase dictionaries win over single-char dictionaries; running each file as
  // its own group converts chars first and leaves the phrase dict's simplified
  // source keys gone (头发→頭發 instead of 頭髮). getDictFiles returns the groups
  // already shaped correctly — this loop just turns file names into dicts.
  const loadGroup = (files: string[]): DictGroup => {
    const group: DictLike[] = [];
    for (const name of files) {
      const dict = loadDictFromModule(name);
      if (dict) group.push(dict);
      else console.warn(`Dictionary ${name} not found. Run 'npm run sync:opencc' first.`);
    }
    return group;
  };

  for (const fileGroup of getDictFiles(options.from, options.to)) {
    const group = loadGroup(fileGroup);
    if (group.length) dictGroups.push(group);
  }

  // (b) CNTWPhrases (ordinary vocabulary dict, stays in main chain)
  const loadPhrases = options.loadCustomPhrases ?? (options.to === "twp" || options.from === "twp");
  if (loadPhrases) {
    const phrases = loadDictFromModule("CNTWPhrases");
    if (phrases) {
      if (options.from === "twp" && options.to === "cn") {
        const reversed = phrases.map(([cn, tw]) => [tw, cn]);
        dictGroups.unshift([reversed]);
      } else {
        dictGroups.unshift([phrases]);
      }
    }
  }

  // (c) Build the inner converter chain
  let convert = ConverterFactory(...dictGroups);

  // (d) User protectedDict wraps as outermost PROTECTED layer (highest priority).
  if (protectedDict) {
    convert = ProtectedConverter(protectedDict, convert);
  }

  return convert;
}

// Re-export types
export type { LocaleCode } from "./presets.js";
export type { DictLike, DictGroup } from "./core.js";
